---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  path: ./clusters/apps/monitoring/grafana/app
  dependsOn:
    - name: longhorn
    - name: reloader
  postBuild:
    substitute:
      APP: grafana
      APP_NAMESPACE: monitoring
  prune: false # Will enable after migration complete
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  timeout: 5m
  wait: false
