---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/sops

resources:
  - intel-gpu-resource-driver/ks.yaml
  - node-feature-discovery/ks.yaml
  - longhorn/ks.yaml
  - backup/ks.yaml
  - snapshot-controller/ks.yaml
  - reloader/ks.yaml
  - descheduler/ks.yaml
  - cilium/ks.yaml
  - coredns/ks.yaml
  - metrics-server/ks.yaml
  - spegel/ks.yaml
  - gateway-api-crds/ks.yaml
