# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/cert-manager.io/certificate_v1.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: erwanleboucher-dev
spec:
  dnsNames:
    - "erwanleboucher.dev"
    - "*.erwanleboucher.dev"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: erwanleboucher-dev-tls
  usages:
    - digital signature
