# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/cert-manager.io/certificate_v1.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: erwanleboucher-dev
spec:
  secretName: erwanleboucher-dev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: erwanleboucher.dev
  dnsNames:
    - "erwanleboucher.dev"
    - "*.erwanleboucher.dev"
