apiVersion: v1
kind: Secret
metadata:
  name: google-drive-backup
type: Opaque
stringData:
  rclone.conf: ENC[AES256_GCM,data:mSvbM3x0Qs7qRNfWAHVFuAQPRw8MQQ4sBSZerZSFIWulPtiM2QKrkvIl8PLuYsR7lhOVCVAyd+omz1RHOgwYJ9JXD00HR8xQdo6iItFgXff7LpvzHvazwohf8Q71TftlvYr63MbSQfweN/dcSbvRVJ1lIENLbxtJEtfhnBoxjMs3l3+B0ucylNtvIIQBtnlCeTR8ErsmjIOh5zaIlv2NBpQ5Dr8XE3K02v0E6nLEPSnSKOfhqKROW+g6r+G697pT/wOo7nwt0te4v0CbmCG7nDPYwbnTiV8Gnz2h7mf20SPJ6EDnVzSAWawPYAw9C8C7dleqcibXFq2NVy5geWzkQ8mQm85/iHnHo7Bn6cQnuFyVaaidOoEmOHGY3h1dzYzsSiRReRlKMnAKMgOENoqQiFvYg/7yZnTrACQcxo2zwd5CDJm6DkmZoGHJFx/6B7mktjtRXHGQf1ex2cexIeWNicfGrHclPEvJ3bjBGyEMOZsuYbU29Ll886a7CsunBj1Ej7FGRSQvuNAPlleKq0LQhjn5xPXthRVMkL3ln3sn6GEgLopaAFC+fXTvuzFMc8FuhGvL0vf2fId6zUEmheJjjpRzwGTV+N4Jh7G7a8+EpYzWiPVHKbs2lvyUsGaVAvKDH34NpLPlWGZyeq5J5mZ/ISrehwz0XTnASrEALzu9GJ9ESKA78yMk4rcLfttkKjlPZg5WQwm5aAcXEKTfcLtHbaOt5XO8nQNk7BAzPjVJnXeqdV1oQ80YEd8DoF7bIebf9yUSfzqd03RiUEoJHK5M64gWmwFQ/Fv11R6U6Lwwfzxie2ZWppQKbTel3zvK7fm3MefcrXp65BL249etipANNHq7d1YsDjvxo8+g/1umz8UM5qDVaEsulqW/LpiRGw==,iv:l/NpdXztZQg79PStUkxKUvvatZu6mD27nfkFB9IuGsk=,tag:skJY/z0xpaNPJZD0bwGJpQ==,type:str]
sops:
  age:
    - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ2o4TjZaSlpGdWpyUHF0
        MDVOVzRKU0tYVHQvVjNMaitrUldXTmU1SGl3Ci92LzdZUDFmL1ZHZjN2ZVlPMTRp
        Qml2ZDNrTVRtOHlGbkNoOXVLWnJTaGcKLS0tIEtiUGRxWDJXaGdGUnQ2dGtaQTRI
        QVk3Y2RCaWd2RkZuY1pGWnZFSjJLMkkKdGziYCwR4wmZbxzFTB9L5/gVQjOm6HZg
        3VvAQ70sYkuPClqN88MWDHlMMdqBbfBsmXLJPNjZFz8QTVLunEl6oQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-02T08:31:53Z"
  mac: ENC[AES256_GCM,data:6RgZPpHC4snrb2xD2ojFE8H6X/SVUmMAer03Jv0LbIqCngYtdGHy4RQkI3zWh2Zl0QM/Exvrl1pIAJtjd1G9CngN+s/nk0134Fe0McDDShzHUzfyfSDV/qKinn10dAnJfM8Up7pRyL/P9gfDzW7tFdI+X/5Ic8+8SqnScRU+AgM=,iv:jPl1fT8qMBPQ/sQ17CuGtw147p425k4YHgDTvIORyOo=,tag:MkSrnGClawtn6Er4aLmlIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
