---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/system/authentik/app
  dependsOn:
    - name: envoy-gateway
    - name: longhorn
    - name: cloudnative-pg
  postBuild:
    substitute:
      APP: authentik
      APP_NAMESPACE: system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: system
  timeout: 10m
  wait: false
