---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:XJkhE2A=,iv:14xTBRIYoGSs/Scr5OaXUlTKdwJOpzrGqNmEWsIZeiw=,tag:ilQhEhhpAPcWRFxGsTn8uQ==,type:str]
  admin-password: ENC[AES256_GCM,data:ThjysAUqmQEgMS3uxr7ZqI1UI7M=,iv:LVLX4rzsYaOUXXi2rQpmIdkz4TxhIx1kUgdMid634fw=,tag:640EzU3DEt1WFYL40s1tTg==,type:str]
sops:
  age:
    - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M1NUSmdUM3IzcUdVbjVn
        Z291S3lFd3JvRVM1UUcvSmtxRDNJRzdZeFJrCkxQd0l4QlA1azFuVkFLMzM0YjFH
        K3BTL2s4b0NIMVhCZHZtYXhwZjRrNkUKLS0tIHFxZHpac09vaTZvTFhmdHBqYXZS
        SER3QjdoYk9XdUF2bmwvTHBubXlwamMKDaQZbUNFN6g1NFsVwuFrMAlWq7naq9WL
        oWnVD9NgFbUr+BDPvI3OqhE/mw5L2L2CsDZI/NVxK2i8Y/0gjkdkkA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T14:24:42Z"
  mac: ENC[AES256_GCM,data:vmAPr8B4BIb58rQJ+1BoEw9oG4Tux5R1LZLgu3xDoVn0NbVxB9c3FFRcGisfwKc25sbPrrCDeXhmeoqKuvRiDoSxzDs71ALWp/Usmr7a8s+ODfh+KVU3/QZluew0lmSxt8FrzAe4eK7r4dupJ9Ij6+xBK4RIvUiZNsQjOWYJgOo=,iv:RaE/OFHq1q33YjurWeOYQl6mDDY41F1oABvrBm+p+yc=,tag:gH5CRAV2/3umMoJQiGXhRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
