---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: nfs-server
spec:
  type: LoadBalancer
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
      protocol: TCP
    - name: mountd
      port: 20048
      targetPort: 20048
      protocol: TCP
    - name: rpcbind
      port: 111
      targetPort: 111
      protocol: TCP
