apiVersion: v1
kind: Secret
metadata:
  name: mikrotik-credentials
stringData:
  username: ENC[AES256_GCM,data:iib82co=,iv:J727Mj2SNu1sodRmgY7GU+hE8RXx5D4JEX3u8czCe6M=,tag:D6Er/s4ipiAFsK7St072Dg==,type:str]
  password: ENC[AES256_GCM,data:hIGEP0We7MLG/Iwh2ns=,iv:8fbZjhR0aiou0AxyzR6yKfpdvkxgaP7qnR1ZM2bOWJU=,tag:5qo2GTNGLB03uXl4z1BRyA==,type:str]
sops:
  age:
    - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMGJySkpINTVCcHFDc2d6
        cWZ6enV6QUlzUUZ4ZEszalM3NDN1RTg1RDBzCjhDL2RwQXMwSURPSjNjMkdtMTZK
        Q3VZME9aaXlycU5vNElhL2RFOTRyeW8KLS0tIGFTalpHaWZwVzkzMWJmU3BTR1lR
        VThKMmZKdzlLVDVyWU9KUjNSd1V2d1EKf///X9wFrjkyy0MZYJaL7oqoio2rxw6P
        o0fkPde/GG4rQtWC+mwMz1f71m4+vC2khV3ohRjjtD/eGz4Z5rOXOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-15T22:54:19Z"
  mac: ENC[AES256_GCM,data:7B05oXOt3ocvNMhIoCF5BOIuf+fDa2qf71xpPYPRpuHuYNJeTd8wpHcznafr7BB+QHOOEvSztRmhsa1rlWvm8tQXRn4/wL+STgg7tUJhZw8qvb1vYPrbvbJPcroT5w+udJEEspJMnucjCJV52yikxq3LVt03m8LhnJt+QkmkMiw=,iv:rK5r9/iBm3TNIDutXfZGpmaF+RBEDQwO1RPyeFSQr2E=,tag:vCQFAOpOewXLNBsBOlitOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
