---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fizzbuzz-staging
spec:
  interval: 1h
  path: ./kubernetes/apps/selfhosted/fizzbuzz/staging
  dependsOn:
    - name: envoy-gateway
      namespace: network
  postBuild:
    substitute:
      APP: fizzbuzz-staging
      APP_NAMESPACE: selfhosted
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fizzbuzz-prod
spec:
  interval: 1h
  path: ./kubernetes/apps/selfhosted/fizzbuzz/prod
  dependsOn:
    - name: envoy-gateway
      namespace: network
  postBuild:
    substitute:
      APP: fizzbuzz-prod
      APP_NAMESPACE: selfhosted
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
