---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/observability.giantswarm.io/silence_v1alpha2.json
apiVersion: observability.giantswarm.io/v1alpha2
kind: Silence
metadata:
  name: kube-cpu-overcommit
spec:
  matchers:
    - name: alertname
      value: KubeCPUOvercommit
