---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/sops

resources:
  - jellyfin/ks.yaml
  - sonarr/ks.yaml
  - radarr/ks.yaml
  - prowlarr/ks.yaml
  - bazarr/ks.yaml
  - jellyseerr/ks.yaml
  - flaresolverr/ks.yaml
  - wizarr/ks.yaml
  - profilarr/ks.yaml
  - streamystats/ks.yaml
  - namespace.yaml
