[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{ config_root }}/talosconfig"
JUST_UNSTABLE = "1"
LEFTHOOK_OUTPUT = "false"

[tools]
"uv" = "latest"
"pipx:flux-local" = "latest"
"aqua:opentofu/opentofu" = "1"
"aqua:google/yamlfmt" = ["latest"]
"aqua:yannh/kubeconform" = "latest"
