---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 6h
  path: ./kubernetes/apps/system/home-assistant/app
  dependsOn:
    - name: envoy-gateway
      namespace: network
    - name: longhorn
      namespace: kube-system
  postBuild:
    substitute:
      APP: home-assistant
      APP_NAMESPACE: system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: system
  timeout: 5m
  wait: false
