---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-schemas
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: k8s-schemas
  interval: 1h
  path: "./kubernetes/apps/jobs/k8s-schemas/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: jobs
  timeout: 5m
  wait: false
