---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - repository.yaml
  - namespace.yaml
  - helmrelease.yaml
  - authelia-middleware.yaml
  - ingress.yaml
