---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 6h
  path: ./kubernetes/apps/system/homepage/app
  dependsOn:
    - name: envoy-gateway
    - name: longhorn
  postBuild:
    substitute:
      APP: homepage
      APP_NAMESPACE: system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: system
  timeout: 5m
  wait: false
