---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vpn-secret.sops.yaml
  - qbitmanage-secret.sops.yaml
  - qbittorrent/ks.yaml
  - sabnzbd/ks.yaml
  - qui/ks.yaml
  - autobrr/ks.yaml
  - cross-seed/ks.yaml
