# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
spec:
  endpoints:
    - dnsName: external.erwanleboucher.dev
      recordType: CNAME
      targets:
        - ${TUNNEL_ID}.cfargotunnel.com
