---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mktxp-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: mktxp-credentials
    template:
      data:
        crs310.yaml: |
          username: "{{ .username }}"
          password: "{{ .password }}"
  dataFrom:
    - extract:
        key: mikrotik-export
