---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: mktxp-config
    files:
      - config/_mktxp.conf
      - config/mktxp.conf

resources:
  - helmrelease.yaml
  - ocirepository.yaml
  - externalsecret.yaml
  - grafanadashboard.yaml
