---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kashalls/kromgo/main/config.schema.json
badge:
  font: Verdana.ttf
  size: 12

metrics:
  - name: talos_version
    query: label_replace(node_os_info{name="Talos"}, "version_id", "$1", "version_id", "v(.+)")
    label: version_id
    title: Talos

  - name: kubernetes_version
    query: label_replace(kubernetes_build_info{service="kubernetes"}, "git_version", "$1", "git_version", "v(.+)")
    label: git_version
    title: Kubernetes

  - name: flux_version
    query: label_replace(flux_instance_info, "revision", "$1", "revision", "v(.+)@sha256:.+")
    label: revision
    title: Flux

  - name: mkt_version
    query: label_replace(mktxp_system_uptime, "short_version", "$1", "version", "([^ ]+).*")
    label: short_version
    title: MikroTik

  - name: cluster_node_count
    query: count(count by (node) (kube_node_status_condition{condition="Ready"}))
    title: Nodes

  - name: cluster_pod_count
    query: sum(kube_pod_status_phase{phase="Running"})
    title: Pods

  - name: github_last_push_info
    query: label_replace(topk(1, github_last_push_info), "short_repo", "$1", "repo", ".+/(.+)")
    label: short_repo
    title: Last Push

  - name: github_last_push_timestamp
    query: topk(1, github_last_push_info)
    title: Last Push Age

  - name: gh_contributions_year
    query: avg (gh_contributions_year)
    title: GH Contributions (1y)

  - name: cluster_latency_over_7d
    query: round(histogram_quantile(0.99, sum(rate(agentgateway_request_duration_seconds_bucket[7d])) by (le)) * 1000)
    title: Gateway Latency
    suffix: "ms"
    colors:
      - color: "green"
        min: 0
        max: 300
      - color: "orange"
        min: 301
        max: 700
      - color: "red"
        min: 701
        max: 9999

  - name: cluster_cpu_usage
    query: round(avg(instance:node_cpu_utilisation:rate5m) * 100, 0.1)
    title: CPU
    suffix: "%"
    colors:
      - color: "green"
        min: 0
        max: 35
      - color: "orange"
        min: 36
        max: 75
      - color: "red"
        min: 76
        max: 9999

  - name: cluster_memory_usage
    query: round(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) * 100, 0.1)
    title: Memory
    suffix: "%"
    colors:
      - color: "green"
        min: 0
        max: 49
      - color: "orange"
        min: 50
        max: 75
      - color: "red"
        min: 76
        max: 9999

  - name: cluster_age_days
    query: round((time() - max(kube_node_created) ) / 86400)
    title: Age
    suffix: "d"
    colors:
      - color: "green"
        min: 0
        max: 180
      - color: "orange"
        min: 181
        max: 360
      - color: "red"
        min: 361
        max: 9999

  - name: cluster_uptime_days
    query: round(avg(node_time_seconds - node_boot_time_seconds) / 86400)
    suffix: "d"
    colors:
      - color: "green"
        min: 0
        max: 180
      - color: "orange"
        min: 181
        max: 360
      - color: "red"
        min: 361
        max: 9999

  - name: cluster_alert_count
    query: ALERTS{alertstate="firing"} - 1
    title: Alerts
    colors:
      - color: "green"
        min: 0
        max: 0
      - color: "red"
        min: 1
        max: 9999
  - name: global_sla
    query: |
      sum(increase(gatus_results_total{success="true"}[7d]))
      /
      sum(increase(gatus_results_total[7d]))
      * 100
    title: SLA (7d)
    suffix: "%"
    colors:
      - color: "green"
        min: 99.9
        max: 100
      - color: "orange"
        min: 99.0
        max: 99.89
      - color: "red"
        min: 0
        max: 98.9
