---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: autobrr
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/apps/downloads/autobrr/app
  dependsOn:
    - name: envoy-gateway
    - name: longhorn
  postBuild:
    substitute:
      APP: autobrr
      APP_NAMESPACE: downloads
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  timeout: 5m
  wait: false
