---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: streamystats-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: streamystats-secret
    creationPolicy: Owner
    template:
      data:
        SESSION_SECRET: "{{ .session_secret }}"
  dataFrom:
    - extract:
        key: streamystats-secret
