---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: streamystats-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: streamystats-secret
    template:
      data:
        SESSION_SECRET: "{{ .session_secret }}"
        DATABASE_URL: "postgresql://{{ .postgres_super_user | urlquery }}:{{ .postgres_super_pass | urlquery }}@postgres-streamystats-rw:5432/streamystats"
        POSTGRES_USER: "{{ .postgres_super_user }}"
        POSTGRES_PASSWORD: "{{ .postgres_super_pass }}"
  dataFrom:
    - extract:
        key: streamystats-secret
    - extract:
        key: cloudnative-pg
