---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ghexp-config
    files:
      - config/config.yaml

resources:
  - helmrelease.yaml
  - ocirepository.yaml
  - externalsecret.yaml
