apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: kube-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:AZP/B3STru0IT+hsF7eKOuqa,iv:KjewgpzlUh+MawL/isIENUHuTtfNhBNrVfwrQJaSOqM=,tag:QUqRpasuAk+Vzl48ulC7xA==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ255UEdsYUhzZ0FLckJN
            ZGp1cWJ3aEhObzhGSUg0Mys0RXpNSjUxcUU4CjVKR0VWK0VtSDFxQytjaGQwMUlF
            dGZvdjh2L096bXpsZkMrK3ZVc3VvNGsKLS0tIFBZYUMxU2hsWCs1d3NSalNiamo4
            Sk9NZzhzYVpKVGZ4OVRnQ2ZmOHJ6bGcK7Fu1Aij676yp7i25u8faJC67puYQ8snq
            7S8a55MNzaXOXU4Yx2zgAIFiYQdGV7HbEWgY99++JKyiDXIFYI39PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-10T22:57:36Z"
    mac: ENC[AES256_GCM,data:j7wTSzkU/hXxfdZQXP3pxP341ss1FGO5+l4Ch3NoJYc6hQiOWY/EvsBYEJgvmf54fO9U2klE7GhioZrU+OiXMvhP/vFRJr6ZzE+nH8BakqTTJbiz3loWqYHyfvENASTKN5w9vzrpcE8UwjO9sx8VHF7SaNSv2SStAV6sIALnbSQ=,iv:JYPFAJpbnoQSZ/wInGPCbrVaIQtP5rgpsZM+JNRljfk=,tag:zqG10PRnOZscGyOpDTtgUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
