apiVersion: v1
kind: Secret
metadata:
    name: sops-age
stringData:
    age.agekey: ENC[AES256_GCM,data:BFTRuKWMXVuOCQ4VAHGkvBsQzIk/i0v6+ZINkPu91AXrcyhyxUIvTwreV1oJc7ix6TqUdOfKReSbFQHgCcGGYjMhqAXBb0uT/54=,iv:gyIk6E2t/U9bj3Wj8HcLPa6LUg9huojlAMrKHBSmRrU=,tag:a9ryQppG6XPHrmuMccw+BA==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcjZyOG90TGp0bmNsYlhh
            THZNNExrQ2pNNnpWMnVsY1hzeEJIVWVjbXhnCmd4S0E4N2F3ZXQrR0JrYWFNUTY4
            TkRVa3lMTEd4b0ZaNzFldWw4eG45QWsKLS0tIERBaTgxUFJsM0tVL0tvMmltZndH
            eWRLVDUrUThOZlU5MEZNNnZ1aWJHME0KlBOVgO1eet4rjRzAOArz+E4vqInRxzmv
            69Cc0WeqCXOk5s9Ww+zP83IPkleqOgDx/jndrvSymHA6JlCxyo16MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T23:01:04Z"
    mac: ENC[AES256_GCM,data:D00f9Wozma5JMAiZgxs3bd10mX2uqeSHkMwv6P6lLWk2sQ+nynfjtm1+kR+PXhSdcaXUlL/QpJj5uD6ca6HRph/NsNg/5HNi6ZVYPWnduwTDjCyngDdTVEM0tzLBPK93EZbbPBMSIEN2AxYlu2icSh8K8CRaipgKGS5fSSq1/Ss=,iv:PKzjun6nSZVpOCtMYqH5RsJtgW0OZxOgp3RurFQCNmI=,tag:/h8KSomFIgvIUbxPxjoaEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
