---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backup
spec:
  interval: 12h
  components:
    - ../../../../components/nfs-media
  path: ./kubernetes/apps/kube-system/backup/app
  dependsOn:
    - name: longhorn
      namespace: kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  timeout: 10m
  wait: false
