---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backup
  namespace: flux-system
spec:
  interval: 12h
  path: ./kubernetes/apps/kube-system/backup/app
  dependsOn:
    - name: longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: backup
  timeout: 10m
  wait: false
