kind: Secret
apiVersion: v1
metadata:
    creationTimestamp: null
    name: google-drive-backup
    namespace: backup
stringData:
    rclone.conf: ENC[AES256_GCM,data:hC0mxS4b/h1c4f3GFxiblQ5KCvdwe0fGqompdgPwAS+oph0WqYXAMHoterGBf9fAAqh54c9qp0SS3EmyCJPxN6vCicpLzQRPa5UO80L8oKDmw9beUmNYF4UfitX3MfWU1lgAW5ROFppgOddKQ/fXwUDxmU4N86w32lpTQW7/BqT3VFujdJWZmn71cJlAiHaR/ogG3hWspYFKKWuDExnMAloW6PZAzspWmV13Cyk4NR6X+xhu6J9dKUCXlBM7oPRVepBTtzpgdk1HG9hDfSj3zLjHhX6vOCiId0EajdlmyYvaaxVmP7AZ41iNznCBGhJUmn4WI5CAwZ61kt7jMjWopioKXVIHH6Sh2+Agk3PdhuW0ooEb06dfJLc2oAyCk7Ha/1Z31IE6riteKWCyRd0SGv2znrruOSaYh+TDcbL0C3AZedeVn96OisHFBKaHhc6kSfbutjVyxRZQvakvtM6itEtrDIggovt4Ao+2dBA1hLQXZ9Yfy9RWEIHbc+dFgM1tEhA9+YQuJamG8JoAtJDhLFZFuBYaGGKeiSmm8DagtPPVz12K1QsGajCfbKwYlMDvUIxdgMq1AY8uV6HvLPfeGoh3ArtWJx+LmYKtP/0D7XibMBkD5VNzZkKpvjmAReIkTGEUC7AUss9bZySsH15PE6m38Y5d+rkLbWYC145WWXk1kbeZVcpE7nmW3Yu/NJpJvckodmcJ1wkpAT0tiHLa9tkGWzYRHkIcYwMC17QvmRaSZFFbP0SeKs8vByisMd11wEjKoRoj6wuKP+xmbVgBb1HoxuGkSFUwtUz65HmR4EtSjz00cJaErX1sDRCVSi7vbj5spQEeXnToMGKDWxLjmu3ob6OStR0ij9o1wd/T5vTuItpSjnQE9WCMAYds,iv:wKWaDTSb07G0Q8B5AIA6xxnSu9kqXG3WggtIB8O1JIs=,tag:ntkDkySi7zJHz7EBN5Wbgw==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aENnV2FaQyt2Yk5iSDRr
            d3RkSlFzaDF3TXJGZ3ZrYTlmc3daaFc0QmdjCmNTNnk1bGRNOGFUSi9YcjREMnNx
            VitoNTVpV3lhZFcyOVBQTWNoM2VaakEKLS0tIDkySlZQRGREcFhxeGcreW81endh
            TUpWQkhLZzJBSXdJM0JDVndmRnFrdFkKY1I+9vj1kkAnr9ytMimJwUcuDtmEvgk/
            lDS8eEP/7qIFGo0hSelAuLSiF107owFzAoSy2aFBCBwh/Pl2EEd5Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T12:01:55Z"
    mac: ENC[AES256_GCM,data:tldA1ZNUjHGKR/jyOXjfF1/Ycp9Lvm1FiizJutYCAR2sFWxepyjxfdlv/fFF3Zn8aT8VVwusxGPqxaqKIbOXOaqoaImaFe/U4bE/66ubhVvhqN4HVIBycDTStdHkzi5xzfk7AZg1j2mlCEt7yw+VG1dQl8zhonheVe9EiMHL+1U=,iv:GKDniYC4qhuRg1y+fgekzRT280cwlkp/9xq8Ff1Mvus=,tag:LOGpn1wxdhYJfGckZj9Lqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
