# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bazarr
  namespace: flux-system
spec:
  components:
    - ../../../../components/nfs-media
    - ../../../../components/volsync
    - ../../../../components/nfs-scaler
  interval: 1h
  path: ./kubernetes/apps/media/bazarr/app
  dependsOn:
    - name: kgateway-gateway
      namespace: network
    - name: longhorn
      namespace: kube-system
    - name: nfs-csi-driver
      namespace: kube-system
    - name: volsync
      namespace: volsync-system
  postBuild:
    substitute:
      APP: bazarr
      APP_NAMESPACE: media
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_SCHEDULE: "30 1-23/2 * * *"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
