---
apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
type: Opaque
stringData:
  age.agekey: ENC[AES256_GCM,data:p4VkvvqJRyaSX84BzMa2NXDzSOfv10s/dU5Sn4+9AKTTCZxvxADwlHAcUNSMxeOCwH1UOcKFBLkWEgnJGUJ5QCcelwKWBVEg8ZA=,iv:MLtow9etKVmpkgXbF5D8R5tbBWH3o/dWnQfYvPM07R0=,tag:6blKF0F1H/7S3OAnQINpKQ==,type:str]
sops:
  age:
    - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdG1tV09hdE9abDVJam1O
        MUxaTERreWc3MmNyRDkyVzgxbGFBUUFtQ2xZCjFhYkFHR3Q4a0lWMEt6V1g0dGVm
        RHpxMDBxMVUxWWtJNjkwam5rVW1BU28KLS0tIFQrMUMvMFYyR1FMVlFtU3NRaUV4
        dC8vb0V4RmJ4YU9za2NWM2ptUnJPa00KEc2n4cyc8wtKznh+uYYDyg+/Bc8UinML
        YLH6dWF1hCukSxSY83DlMT51ewnbKOusnEKryRtxNjs4gqJ4PXHI5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T14:24:56Z"
  mac: ENC[AES256_GCM,data:8PNXxJbE3Hz/VsZbCJ7lpMhWPrGQgMliJ3/ucMVdyjGCyS5a7z0bkuH8Ehfs2RiZzjXGV09LWXLkk4q4Tbv4bZ28xtXA6ie92udAN97o4Yazh9BuwHD5zV7oXmk8g6yxk54QbhEZoQOSpzuUmuOnjJhW2x9QN59IKIZlL3EqzQk=,iv:s84UNKKGJGK3A48F2U8DqvgjRpTLs8vcpNrQfbWD/N0=,tag:31i4UctlIEOfdGo8y19BdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
