---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-${APP_NAMESPACE}
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions:
    - nfsvers=4.2
    - nconnect=16
    - hard
    - timeo=100
    - retrans=5
    - noatime
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: normandie.internal#/#
    volumeAttributes:
      server: "normandie.internal"
      share: "/"
