---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  volumeName: nfs-media-${APP_NAMESPACE}
  resources:
    requests:
      storage: 500Gi
