---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../components/sops

resources:
  - namespace.yaml
  - qbittorrent/ks.yaml
  - sabnzbd/ks.yaml
  - qui/ks.yaml
  - autobrr/ks.yaml
