# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: discord-webhook
    creationPolicy: Owner
    template:
      data:
        WEBHOOK_URL: "{{ .webhook_url }}"
  data:
    - secretKey: webhook_url
      remoteRef:
        key: discord-webhook
