---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  - ../../components/sops

resources:
  - namespace.yaml
  - externalsecret.yaml
  - beszel/ks.yaml
  - kube-prometheus-stack/ks.yaml
  - gatus/ks.yaml
  - grafana/ks.yaml
  - fluent-bit/ks.yaml
  - victoria-logs/ks.yaml
  - mikrotik-exporter/ks.yaml
  - headlamp/ks.yaml
  - kromgo/ks.yaml
  - github-exporter/ks.yaml
