---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  - ../../components/sops

resources:
  - namespace.yaml
  - externalsecret.yaml
  - beszel/ks.yaml
  - speedtest-tracker/ks.yaml
  - kube-prometheus-stack/ks.yaml
  - gatus/ks.yaml
