---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mealie
spec:
  components:
    - ../../../../components/cnpg
    - ../../../../components/volsync
  dependsOn:
    - name: kgateway-gateway
      namespace: network
    - name: longhorn
      namespace: kube-system
    - name: cloudnative-pg
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/selfhosted/mealie/app
  postBuild:
    substitute:
      APP: *app
      APP_NAMESPACE: selfhosted
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_SCHEDULE: "20 1-23/2 * * *"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
