---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/automation/renovate-operator/app
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: renovate-operator
      namespace: automation
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: automation
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-jobs
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/automation/renovate-operator/jobs
  dependsOn:
    - name: renovate-operator
    - name: external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: automation
  timeout: 5m
  wait: false
