---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  components:
    - ../../../../components/volsync
    - ../../../../components/cnpg
    - ../../../../components/nfs-scaler
  dependsOn:
    - name: longhorn
      namespace: kube-system
  interval: 1h
  path: "./kubernetes/apps/selfhosted/paperless/app"
  postBuild:
    substitute:
      APP: paperless
      APP_UID: "1000"
      APP_GID: "65542"
      VOLSYNC_CLAIM: paperless-data
      VOLSYNC_CAPACITY: 15Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
