---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-dns
spec:
  interval: 6h
  path: ./kubernetes/apps/network/external-dns/cloudflare-dns
  postBuild:
    substitute:
      APP: cloudflare-dns
      APP_NAMESPACE: network
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mikrotik-dns
spec:
  interval: 6h
  path: ./kubernetes/apps/network/external-dns/mikrotik-dns
  postBuild:
    substitute:
      APP: mikrotik-dns
      APP_NAMESPACE: network
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
  wait: false
