---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lingarr
  namespace: flux-system
spec:
  components:
    - ../../../../components/nfs-media
  interval: 1h
  path: ./kubernetes/apps/media/lingarr/app
  postBuild:
    substitute:
      APP: lingarr
      APP_NAMESPACE: media
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
