---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: volsync
spec:
  interval: 1h
  path: ./kubernetes/apps/volsync-system/volsync/app
  dependsOn:
    - name: longhorn
      namespace: kube-system
    - name: snapshot-controller
      namespace: kube-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: volsync
      namespace: volsync
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: volsync-system
  timeout: 10m
  wait: true
