---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-erwanleboucher-dev
  namespace: network
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.erwanleboucher.dev"
    - "erwanleboucher.dev"
