# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
spec:
  interval: 6h
  path: ./kubernetes/apps/network/cloudflared/app
  dependsOn:
    - name: external-secrets
      namespace: security
  postBuild:
    substitute:
      APP: cloudflared
    substituteFrom:
      - kind: Secret
        name: cloudflared-token
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
  timeout: 5m
  wait: false
