---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agentgateway
spec:
  endpoints:
    - interval: 1m
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 30s
  jobLabel: agentgateway
  namespaceSelector:
    matchNames:
      - network
  selector:
    matchLabels:
      app.kubernetes.io/name: agentgateway
