# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qui
  namespace: flux-system
spec:
  components:
    - ../../../../components/nfs-media
    - ../../../../components/volsync
    - ../../../../components/nfs-scaler
  interval: 1h
  path: ./kubernetes/apps/downloads/qui/app
  dependsOn:
    - name: agentgateway-gateway
      namespace: network
    - name: longhorn
      namespace: kube-system
    - name: nfs-csi-driver
      namespace: kube-system
  postBuild:
    substitute:
      APP: qui
      APP_NAMESPACE: downloads
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_SCHEDULE: "20 1-23/2 * * *"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  timeout: 5m
  wait: false
