---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../components/sops

resources:
  - namespace.yaml
  - bentopdf/ks.yaml
  - mealie/ks.yaml
  - atuin/ks.yaml
  - fizzbuzz/ks.yaml
  - libretranslate/ks.yaml
