---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - externalsecret.yaml
  - externalsecret-postgres.yaml
  - secret.sops.yaml
  - postgres-credentials.sops.yaml
  - postgres-cluster.yaml
  - helmrelease.yaml
  - httproute.yaml
