# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app streamystats
  namespace: flux-system
spec:
  interval: 1h
  components:
    - ../../../../components/cnpg
  path: ./kubernetes/apps/media/streamystats/app
  dependsOn:
    - name: envoy-gateway
      namespace: network
    - name: longhorn
      namespace: kube-system
    - name: external-secrets
      namespace: security
    - name: cloudnative-pg
      namespace: database
  prune: true
  postBuild:
    substitute:
      APP: *app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
