---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app streamystats
  namespace: flux-system
spec:
  interval: 1h
  components:
    - ../../../../components/cnpg
  path: ./kubernetes/apps/media/streamystats/app
  dependsOn:
    - name: envoy-gateway
    - name: longhorn
  prune: true
  postBuild:
    substitute:
      APP: *app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
