# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: beszel
  namespace: flux-system
spec:
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: longhorn
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/monitoring/beszel/app
  postBuild:
    substitute:
      APP: beszel
      APP_NAMESPACE: monitoring
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_SCHEDULE: "0 1-23/2 * * *"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  timeout: 5m
  wait: false
