---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: beszel
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/monitoring/beszel/app
  dependsOn:
    - name: longhorn
      namespace: kube-system
  postBuild:
    substitute:
      APP: beszel
      APP_NAMESPACE: monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  timeout: 5m
  wait: false
