---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: csi-driver-nfs
      version: "4.12.1"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system

  values:
    controller:
      name: csi-nfs-controller
      replicas: 1
      runOnControlPlane: true
    node:
      name: csi-nfs-node
      maxUnavailable: 1
    externalSnapshotter:
      enabled: false
    feature:
      enableFSGroupPolicy: true
      enableInlineVolume: false
