---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.sops.yaml
  - beszel/ks.yaml
  - speedtest-tracker/ks.yaml
  - prometheus/ks.yaml
  - gatus/ks.yaml
