---
apiVersion: v1
kind: Secret
metadata:
  name: beszel-token
  namespace: monitoring
type: Opaque
stringData:
  KEY: ENC[AES256_GCM,data:/c9EuiRFNftWTRsvXY5DX+IltKTwg2bHNKb0jeA8beaXRQaHKuavPoQ45piWghtQtKA5aNX60FKik735JM9shfQtPOms8pJ9U6C6vJV/YiA=,iv:K064SwsFTxEJWJmGYJL8TpXJn22kcArDccjzcQPD3PY=,tag:i8oB7LDm4anmTVUmP+gF6g==,type:str]
  TOKEN: ENC[AES256_GCM,data:lpUAGW1YdK3ZEV8Ga+Ua4QJCeQ1uCUAkpf3u9v/UMJHWDpUZ,iv:shv2uFMh7t9WOD/4L5FGeCi85YJ/BCOl7c5iV/M57Bw=,tag:28QEzkX0TJ9ITHl+OI9FUA==,type:str]
sops:
  age:
    - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSDBLNUJhOTdSR3RpL0Ra
        RE00WVg4U2xIUTdOR0tCY1NlY1RnclBZbFZjClR4cTMyT2xoZ21uMVowT2hsWi8x
        N3Mzd1ljZHVEZ1RTNUFISVVxODRIYlEKLS0tIC9qdjJjaDZjaGZqdGhLR1lkSVdY
        QVNSTml6WFVKVm0rQkFJM1hxcTZsZVkK72ITE/7qgH6KYiMSKCrXE79z5YfMsBRi
        YOw72FMnNGLvjLDYwK7v7cS3WuCrfIGDXICr9RDipT81XuPIlzEPlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T21:16:05Z"
  mac: ENC[AES256_GCM,data:vgGPy/enKR4Jc9PFyF6DR1ChGy28nN7TmIwFKdPvgtNrtx55rgjiOBI/eKaZVVB2OmUVnOk/gKdPw0MR7DMvdl8WLqQftZMn5XATaiUGLLfpauJB4qqetJszhApT18MQKZXA3mckjxS3w1Yosa3GD5EL/Dpj4cPcswiK5Fj+on0=,iv:iHjWeoUDzr3MJ/Dl1Swdq8afikJ3ZOfLdvMoND7fn5s=,tag:7lH/2wariMgGEPvmrYpJig==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
