apiVersion: v1
kind: Secret
metadata:
    name: beszel-token
    namespace: monitoring
type: Opaque
stringData:
    KEY: ENC[AES256_GCM,data:/c9EuiRFNftWTRsvXY5DX+IltKTwg2bHNKb0jeA8beaXRQaHKuavPoQ45piWghtQtKA5aNX60FKik735JM9shfQtPOms8pJ9U6C6vJV/YiA=,iv:K064SwsFTxEJWJmGYJL8TpXJn22kcArDccjzcQPD3PY=,tag:i8oB7LDm4anmTVUmP+gF6g==,type:str]
    TOKEN: ENC[AES256_GCM,data:bVaXjWSAzmp1DqwX9IJbsErS3QIRounRPq3fMSihZinHR7gk,iv:APGZj6XWG/vA+i2h+kZWpbYPEbSSJXe8/x25EzJME1A=,tag:DP942440Bde9zcEkWN2DrQ==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSDBLNUJhOTdSR3RpL0Ra
            RE00WVg4U2xIUTdOR0tCY1NlY1RnclBZbFZjClR4cTMyT2xoZ21uMVowT2hsWi8x
            N3Mzd1ljZHVEZ1RTNUFISVVxODRIYlEKLS0tIC9qdjJjaDZjaGZqdGhLR1lkSVdY
            QVNSTml6WFVKVm0rQkFJM1hxcTZsZVkK72ITE/7qgH6KYiMSKCrXE79z5YfMsBRi
            YOw72FMnNGLvjLDYwK7v7cS3WuCrfIGDXICr9RDipT81XuPIlzEPlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T12:46:26Z"
    mac: ENC[AES256_GCM,data:HJQljNgrG1F+MEBZJjNeIZ03YGOIZsYc+UtUa1G7wOskMUgiTmYEhihpnSDo0xM/rw0YFhh9Be3VhfkpqlAglsXSsQ8DnACWcaCGmqJ7NZl+woOmCcIfK0XaZJ1ibKjH+xyu41FsVGAaUaO9uwIGgvuGYa47myit3vI4HAwqOrs=,iv:eoiypRdqu9CeTwv/AyTZNdI9pylQIW+gSkjjOVkyqqU=,tag:6pUpl4va7KaVFOCIOwS+uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
