apiVersion: v1
kind: Secret
metadata:
    name: beszel-token
    namespace: monitoring
type: Opaque
stringData:
    KEY: ENC[AES256_GCM,data:vBLFfN8em1ptdmY5VJZZOiBL6hOlpEfiVpOCbRkIrfWaLodnvrzNt48SNv6wZynB7yrtZHZckHDGCQbWdaEiEICebEru3fC6whXmCL7m7H8=,iv:5NRY9Q0d7liHySWT9OhI9aiJBGpb3gjEjyX+D+k4Apw=,tag:KVsDQK8kTeqYQ1JQNh2BRQ==,type:str]
    TOKEN: ENC[AES256_GCM,data:QykrrNcvmahlWsrmkwW83ToYjJMwhsCH0JE/2q0FvjCqjDqe,iv:Hq0c8xQodJVSGiHiGPj7QC0J72sG+whrRBuKNSKnLh4=,tag:KSu0LOujxNl5ie7ncAgEbw==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSDBLNUJhOTdSR3RpL0Ra
            RE00WVg4U2xIUTdOR0tCY1NlY1RnclBZbFZjClR4cTMyT2xoZ21uMVowT2hsWi8x
            N3Mzd1ljZHVEZ1RTNUFISVVxODRIYlEKLS0tIC9qdjJjaDZjaGZqdGhLR1lkSVdY
            QVNSTml6WFVKVm0rQkFJM1hxcTZsZVkK72ITE/7qgH6KYiMSKCrXE79z5YfMsBRi
            YOw72FMnNGLvjLDYwK7v7cS3WuCrfIGDXICr9RDipT81XuPIlzEPlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T15:28:57Z"
    mac: ENC[AES256_GCM,data:u02c36Wt3wvzrTnMCE/B454YuMWkvqK/x6hlQkNEH4mhpYypqa5d5QA5bNPIB9krAPgSolqWCd8ctixK48IFz5AdOQ04WWxDcSaAIaH2lt850D54EBkZffcoWIES0qWmu1KQY0YZsBgcBM0kezPvhaRnuQm9VHSEHmNmMTG0z7g=,iv:kUBtixKAvWC3o4zSavJFxjs7jjJrq66hOH63lrJKwfY=,tag:nZPMxEEI65HvCOgylgsVEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
