---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
spec:
  components:
    - ../../../../components/nfs-media
  interval: 1h
  path: ./kubernetes/apps/media/sonarr/app
  dependsOn:
    - name: envoy-gateway
      namespace: network
    - name: longhorn
      namespace: kube-system
    - name: nfs-server
      namespace: nfs-server
    - name: nfs-csi-driver
  postBuild:
    substitute:
      APP: sonarr
      APP_NAMESPACE: media
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
