---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: speedtest-tracker
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/monitoring/speedtest-tracker/app
  dependsOn:
    - name: longhorn
  postBuild:
    substitute:
      APP: speedtest-tracker
      APP_NAMESPACE: monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: monitoring
  timeout: 5m
  wait: false
