---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
components:
  - ../../components/sops

resources:
  - namespace.yaml
  - home-assistant/ks.yaml
  - homepage/ks.yaml
  - mikrotik-cert-sync/ks.yaml
  - smtp-relay/ks.yaml
