---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - adguard/ks.yaml
  - home-assistant/ks.yaml
  - cloudflared/ks.yaml
  - homepage/ks.yaml
  - smtp-relay/ks.yaml
