---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bentopdf
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/selfhosted/bentopdf/app
  dependsOn:
    - name: envoy-gateway
      namespace: network
    - name: longhorn
      namespace: kube-system
  postBuild:
    substitute:
      APP: bentopdf
      APP_NAMESPACE: selfhosted
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
