---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: adguard
  namespace: flux-system
spec:
  interval: 6h
  path: ./kubernetes/apps/system/adguard/app
  dependsOn:
    - name: envoy-gateway
      namespace: network
    - name: longhorn
      namespace: kube-system
  postBuild:
    substitute:
      APP: adguard
      APP_NAMESPACE: adguard
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: adguard
  timeout: 10m
  wait: false
