---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mikrotik-cert-sync
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mikrotik-cert-sync
  namespace: network
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    resourceNames:
      - "erwanleboucher-dev-tls"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mikrotik-cert-sync
  namespace: network
subjects:
  - kind: ServiceAccount
    name: mikrotik-cert-sync
    namespace: system
roleRef:
  kind: Role
  name: mikrotik-cert-sync
  apiGroup: rbac.authorization.k8s.io
