---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: flux-system
spec:
  interval: 6h
  path: ./kubernetes/apps/system/cloudflared/app
  dependsOn:
    - name: external-secrets
      namespace: security

  postBuild:
    substitute:
      APP: cloudflared
      APP_NAMESPACE: system
    substituteFrom:
      - kind: Secret
        name: cluster-vars
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: system
  timeout: 5m
  wait: false
