# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chartRef:
    kind: OCIRepository
    name: longhorn
  interval: 1h
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
      disableRevisionCounter: "true"
    defaultBackupStore:
      backupTarget: "nfs://192.168.1.40:/backups/longhorn-backups"
      backupTargetCredentialSecret: ""
    defaultSettings:
      defaultDataPath: /var/mnt/longhorn
      defaultLonghornStaticStorageClass: longhorn
      createDefaultDiskLabeledNodes: true
      restoreVolumeRecurringJobs: true
      guaranteedEngineManagerCPU: "20"
      guaranteedReplicaManagerCPU: "20"
      defaultDataLocality: best-effort
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      orphanAutoDeletion: true
      replicaAutoBalance: best-effort
      storageMinimalAvailablePercentage: "1"
      allowRecurringJobWhileVolumeDetached: true
      defaultReplicaCount: "2"
      replicaSoftAntiAffinity: true
      replicaDiskSoftAntiAffinity: true
      replicaZoneSoftAntiAffinity: true
      orphanResourceAutoDeletion: "replica-data;instance"
      backupCompressionMethod: "lz4"

    longhornUI:
      replicas: 1
    metrics:
      serviceMonitor:
        enabled: true
