---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.10.1
  interval: 1m0s
  values:
    annotations:
      reloader.stakater.com/auto: "true"
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
      disableRevisionCounter: "true"
    defaultBackupStore:
      backupTarget: "nfs://192.168.1.63:/backups/longhorn-backups"
      backupTargetCredentialSecret: ""
    defaultSettings:
      defaultDataPath: /var/mnt/longhorn
      defaultLonghornStaticStorageClass: longhorn
      createDefaultDiskLabeledNodes: true
      guaranteedEngineManagerCPU: "30"
      guaranteedReplicaManagerCPU: "30"
      defaultDataLocality: best-effort
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      orphanAutoDeletion: true
      replicaAutoBalance: best-effort
      storageMinimalAvailablePercentage: "1"
      allowRecurringJobWhileVolumeDetached: true
      defaultReplicaCount: "2"
      replicaSoftAntiAffinity: true
      replicaDiskSoftAntiAffinity: false
      replicaZoneSoftAntiAffinity: false
      orphanResourceAutoDeletion: "replica-data;instance"
      backupCompressionMethod: "lz4"

    longhornUI:
      replicas: 1
