# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/snapshot.storage.k8s.io/volumesnapshotclass_v1.json
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/snapshot.storage.k8s.io/volumesnapshotclass_v1.json
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn
driver: driver.longhorn.io
deletionPolicy: Delete
