---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/ks.yaml
  - traefik/ks.yaml
  - helm-repos/ks.yaml
  - intel-device-plugins-operator/ks.yaml
  - node-feature-discovery/ks.yaml
  - longhorn/ks.yaml
  - envoy
  - backup/ks.yaml
  - metallb/ks.yaml
  - snapshot-controller/ks.yaml
  - system-upgrade-controller/ks.yaml
  - reloader/ks.yaml
