---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - traefik
  - helm-repos
  - intel-device-plugins-operator
  - node-feature-discovery
  - longhorn
  - backup
  - metallb
  - snapshot-controller
  - system-upgrade-controller
