# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  components:
    - ../../../../components/gpu
    - ../../../../components/volsync
    - ../../../../components/nfs-scaler
    - ../../../../components/kgateway-trafficpolicy
  interval: 1h
  path: ./kubernetes/apps/media/jellyfin/app
  dependsOn:
    - name: kgateway-gateway
      namespace: network
    - name: longhorn
      namespace: kube-system
  postBuild:
    substitute:
      APP: jellyfin
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_SCHEDULE: "50 1-23/2 * * *"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false
