---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: paperless
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/instance: paperless
      app.kubernetes.io/controller: paperless
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: network
            gateway.networking.k8s.io/gateway-name: kgateway-internal
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: paperless
            app.kubernetes.io/instance: paperless
            app.kubernetes.io/service: paperless-redis
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: postgresql
            app.kubernetes.io/instance: postgres-paperless
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: paperless-redis
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: paperless
      app.kubernetes.io/instance: paperless
      app.kubernetes.io/service: paperless-redis
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: paperless
            app.kubernetes.io/instance: paperless
            app.kubernetes.io/controller: paperless
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/cilium.io/ciliumnetworkpolicy_v2.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: paperless-pgsql
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: postgres-paperless
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: paperless
            app.kubernetes.io/instance: paperless
            app.kubernetes.io/controller: paperless
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
