apiVersion: v1
stringData:
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:INAeB3uMG9TW7c3AWrSFmYj2ZttrepNP9xlLhA==,iv:WzZ2tMsgVCw2nA+D9D2lQGywrtdIjEvWj7YjdRiNLxw=,tag:YDUVz4b/GdoTeJvkihxLNg==,type:str]
kind: Secret
metadata:
  name: paperless-secret
sops:
  age:
    - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S0FLKzJ4R3liT1dGWEpN
        VHNrcEZoNEtMSWRxOHA1MjVMNEgzQlR0bkV3CmJDTU9oVXpEYW5VWE45YTlkd3h3
        emwycm1OWnN1VGZKRjROeURCellFaTAKLS0tIGZ1SjdxWm5IQVJiK1l4eFl3cDJj
        ZStOQndTVzc0aDlyL2RzY2hNaUlIckkKevoPot93Cs8MgopUFnCPVnQFgRdvXEM0
        Typ+Cw7yg/ZqfmSsb1I5HnUTHJjiFZx/UV6I6WdhvnSboqaDBmKmmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T13:21:47Z"
  mac: ENC[AES256_GCM,data:t4U7PPTfPzRKM4iJjdkTa+YBptAV9eDUSxWAjFbL2KYG1x2IuMXZ9F49LsTEb51f6Y3UfSqj2FJSl4KbsVHuNt5shFPqBS4e0R60k5FePM0jhxwtnApw4eejrZ9aDbczsX3rLvyFYQ5R28izOhcLAhpE7ajv8helMAqkTYV277A=,iv:uPAgkySW/EzeCgVRYv/WCjsBte98sFe9H8S20beL6Xw=,tag:Q/2b7rDybxuJWArDtJ4oFw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
