# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/clustersecretstore_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security.svc.cluster.local:9998
      organizationID: b811d4bd-13c7-4bfc-9886-b3a9016640cc
      projectID: dfbc272d-bc7b-4474-b408-b3a901665a55
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: security
        key: ca.crt
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            namespace: security
            key: token
