kind: Secret
apiVersion: v1
metadata:
    creationTimestamp: null
    name: google-drive-backup
    namespace: backup
stringData:
    rclone.conf: ENC[AES256_GCM,data:SybyocXiZkVzjdfFH6LTw6MQ7PAigHucBj48U3In5n8vEKjGjCuSCtBqDtgWBg/jkN1srhTRVEDLIdDdIV26uFcLhWVcfDQMvkA1i/ViFZZLx0ONb1/93IGBJOcGQMCIz8B0ShBKyVOjMco1oB5NyIogw+HZZb417XI+9gb5nuOnbCTtdENt/zSWLczwC5GHXLMT5748GUxURXRMfIUFg+p9fBNoOVDCstkII55b6Ob6g/ccXVtpBGhYwSnKzcdB2rOFfuL0qBGSSQ0j6xFcF3MOT4k4XgI35yiApyp5Dnxtw3uVHqr754MvDx/lGatsAmu9fR+IXXr84l4AoYFHqs02SU69BZQ/Mk1Nuth6BgV/8JaXIxi9haBIEW3+BrX+CjPzjI+YtCYPHEjU47PqrZ5/xrhmHVmPW9N33bRdriDj6pzcBsw0PlamBIWpubLaYxs8GOI5kXWHKYmwN6ULAzYHOfeVRn0o+GC7oekCN/At2N4IAxic0/5Mn7IQsa9duyp3akvcy/0T6+SM68kadlw1QmnerHFi9rO4jG2VMLN0yhrp+ddw8PwU8cpFnjMiUCu8Y20hJ7htqAp+QnjhGEmQ//LIO5YoA7I45tgfc1Lm+IMJEyQIInoldhszXokJxgzZZvibrxlckQTNOD8H692hjCAT+qli9cVhw1h2RY5VK1uI1K3Oy1ICZTVbVgrXCz2xPP8+3Xnei5hryKzJNRxW5gIvVswNhJOX3gjrt8PM+Rb8rIxATBt7ka9eweO2QKahwJelFo7MSxbkchfi3LRlW9PKU2vxMfzCpc7zNckB/lFRCOPWWdI4BLBs886zt8f5v9GpPue8xdAcx6j1MCapjHxPvSSyrWvQzGKAfnNQepscDue7v6CYlQqx,iv:s92hx57kRuS5EjEbDEqAmYzStsavEnAqPOyYVyGQsTA=,tag:S1tUvYazAs/MvGzzLXg9/w==,type:str]
sops:
    age:
        - recipient: age120vrfse9e0hexvlr70rensn2myph7r0n9yevr5dvgur0l8gf2dxqpmut7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aENnV2FaQyt2Yk5iSDRr
            d3RkSlFzaDF3TXJGZ3ZrYTlmc3daaFc0QmdjCmNTNnk1bGRNOGFUSi9YcjREMnNx
            VitoNTVpV3lhZFcyOVBQTWNoM2VaakEKLS0tIDkySlZQRGREcFhxeGcreW81endh
            TUpWQkhLZzJBSXdJM0JDVndmRnFrdFkKY1I+9vj1kkAnr9ytMimJwUcuDtmEvgk/
            lDS8eEP/7qIFGo0hSelAuLSiF107owFzAoSy2aFBCBwh/Pl2EEd5Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T11:56:08Z"
    mac: ENC[AES256_GCM,data:a9tKxFjHIiHBOAZh1bTzm9Qpn6q4oJIWYWnqTJhjJeZ2sfTlRt8gLsIh/AIJu9xlEhWdP+99QwugmYVAfMyFwKbYrKrq0lAqPMyBWm3MLvfmw640zy+opVB1C5NwDbnZkL7ymcdFeSvqnY+Dz75z+XL2mg2ZNepgjFDYwqrzXm8=,iv:897lfoks7i+ezfnpdFXj6I7/IjInB8MTYtkn9gaOqkQ=,tag:n8W2p3WJvvUk0pW5EiKv9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
