---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: publish-k8s-schemas-secrets
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: publish-k8s-schemas-secret
    creationPolicy: Owner
    template:
      data:
        CLOUDFLARE_ACCOUNT_ID: "{{ .cloudflare_account_id }}"
        CLOUDFLARE_API_TOKEN: "{{ .cloudflare_api_token }}"
  dataFrom:
    - extract:
        key: cloudlare-k8s-schemas
