---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk-server
  namespace: security
spec:
  secretName: bitwarden-tls-certs
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - homelab
  commonName: bitwarden-sdk-server.security.svc.cluster.local
  dnsNames:
    - bitwarden-sdk-server
    - bitwarden-sdk-server.security
    - bitwarden-sdk-server.security.svc
    - bitwarden-sdk-server.security.svc.cluster.local
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
    group: cert-manager.io
