# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudflared-token
    creationPolicy: Owner
    template:
      data:
        TUNNEL_TOKEN: "{{ .tunnel_token }}"
        TUNNEL_ID: "{{ .tunnel_id }}"
        ACCOUNT_ID: "{{ .account_id }}"
  dataFrom:
    - extract:
        key: cloudflared-token
