---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudflared-token
    creationPolicy: Owner
    template:
      data:
        TUNNEL_TOKEN: "{{ .tunnel_token }}"
        TUNNEL_ID: "{{ .tunnel_id }}"
  dataFrom:
    - extract:
        key: cloudflared-token
