---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

components:
  - ../../components/sops

resources:
  - namespace.yaml
  - externalsecret.yaml
  - envoy/ks.yaml
  - external-dns/ks.yaml
  - cloudflared/ks.yaml
  - echo/ks.yaml
