---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kgateway-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: &loadBalancerIP "192.168.69.10"
    gatus.home-operations.com/endpoint: |-
      group: internal
      guarded: true
      ui:
        hide-hostname: true
        hide-url: true
spec:
  gatewayClassName: kgateway
  addresses:
    - type: IPAddress
      value: *loadBalancerIP
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/target: *loadBalancerIP
      lbipam.cilium.io/ips: *loadBalancerIP
    parametersRef:
      name: kgateway-params
      group: gateway.kgateway.dev
      kind: GatewayParameters
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.erwanleboucher.dev"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: erwanleboucher-dev-tls
---
# yaml-language-server: $schema=https://k8s-schemas.erwanleboucher.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kgateway-internal
spec:
  jobLabel: kgateway-internal
  namespaceSelector:
    matchNames:
      - network
  podMetricsEndpoints:
    - port: http-monitoring
      path: /metrics
      honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: kgateway-internal
