---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gatewayparams.yaml
  - ./certificate.yaml
  - ./internal.yaml
  - ./httplistenerpolicy.yaml
  - ./external.yaml
  - ./https-redirect.yaml
  - ./trafficpolicy.yaml

